### ISSUE TITLE
Got this error when play the srt stream.

### ISSUE THREAD

**Issue by Earyongan** [ThibaultBee/SrtPlayer#2]
Playback error com.google.android.exoplayer2.ExoPlaybackException: Source error

**Comment by Earyongan** [comment]
is it correct to set like this?

```
val url = "srt://live.cloudflare.com:778";
val passphrase = ""
var mediaId = "";

val mediaItem = MediaItem.Builder()
    .setMediaId(mediaId)
    .setUri(url)
    /**
     * From SRT socket option: "The password must be minimum 10 and maximum
     * 79 characters long."
     */
    .setCustomCacheKey(passphrase)
    .build()
```

**Comment by Earyongan** [comment]
![Screenshot_1700623266](https://github.com/ThibaultBee/SrtPlayer/assets/80608485/9bfcaf70-daf4-4651-b316-cacfca1fda63)

**Comment by ThibaultBee** [comment]
Hello there,

Your URL looks like a contribution URL (from camera to server) and not a delivery (from server to player). It would be weird that Cloudflare uses SRT for delivery. If it is a contribution URL, it don't understand what you are trying to achieve. Contact cloudflare support.

I suppose `setMediaId` is your `streamid`.
See https://github.com/ThibaultBee/SrtPlayer/blob/73aa675e2238698ab3bd0b0c51b581efbd3c35be/README.md?plain=1#L35

Finally, you should keep your id and passphrase secret.

**Comment by Earyongan** [comment]
```
    "srt": {
      "url": "srt://live.cloudflare.com:778",
      "streamId": "...",
      "passphrase": "..."
    },
    "srtPlayback": {
      "url": "srt://live.cloudflare.com:778",
      "streamId": "...",
      "passphrase": "..."
    },
This is the response from cloudflare, and I want to playback with srtplayback, is it possible? I use ffmpeg to test and it working.
```

**Comment by ThibaultBee** [comment]
As I said, see
https://github.com/ThibaultBee/SrtPlayer/blob/73aa675e2238698ab3bd0b0c51b581efbd3c35be/README.md?plain=1#L35



```
val url = "srt://live.cloudflare.com:778?streamid=mystream";
val passphrase = "mypassphrase"

val mediaItem = MediaItem.Builder()
    .setUri(url)
    /**
     * From SRT socket option: "The password must be minimum 10 and maximum
     * 79 characters long."
     */
    .setCustomCacheKey(passphrase)
    .build()
```

I think this should be okay.

**Comment by Earyongan** [comment]
```
2023-11-25 02:13:19.373  7436-7480  CCodec                  io.github.thibaultbee.srtplayer      D  setup formats output: AMessage(what = 0x00000000) = {
int32_t android._color-format = 2135033992
int32_t android._video-scaling = 1
int32_t rotation-degrees = 0
int32_t color-standard = 1
int32_t color-range = 2
int32_t color-transfer = 3
int32_t sar-height = 1
int32_t sar-width = 1
Rect crop(0, 0, 1279, 719)
int32_t width = 1280
int32_t height = 720
int32_t max-height = 720
int32_t max-width = 1280
string mime = "video/raw"
int32_t android._dataspace = 260
int32_t color-format = 2130708361
}

```

And the screen show black screen

**Comment by Earyongan** [comment]
It working fine when I testing with ffplay

**Comment by ThibaultBee** [comment]
Nice. You did connect.
The stream has been decoded.

I am sorry, I don't want to spend much time on the maintenance. Here are a few things that could help you:
- Could you try to test with an older commit?
- Could you try to increase latency?

**Comment by Earyongan** [comment]
I already test with older commit and increase the latenc, but the player show only black screen.

**Comment by umairsajid0017** [comment]
Yes Same problem, FFplay is playing but This media player is not

**Comment by ThibaultBee** [comment]
Hi,

Did you fix the issue? If yes, how?
